# Basics of Numpy

- Numpy, Short for Numerical Python, is one of the most important fundamental package for numerical computing.
Numpy’s main object is the homogeneous multidimensional array. It is a table of elements (usually numbers), all of the same type, indexed by a tuple of positive integers. In Numpy dimensions are called axes. The number of axes is rank.

In [ ]:
!pip install numpy   # jupyter or python or ipython

# terminal
pip install numpy  
conda install numpy

In [40]:
import numpy as np

In [60]:
a=np.arange(15).reshape(5,3)
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [61]:
a.shape

(5, 3)

In [62]:
a.dtype.name

'int64'

In [63]:
type(a)

numpy.ndarray

In [64]:
a.size

15

# Array creation

There are several ways to create arrays.

you can create an array from a regular Python list or tuple using the array function. 
The type of the resulting array is deduced from the type of the elements in the sequences.

In [65]:
a=np.array([3,5,7])
a

array([3, 5, 7])

In [66]:
b=np.array([3.2,4.6,6.7])
b

array([3.2, 4.6, 6.7])

In [67]:
b.dtype.name

'float64'

In [68]:
c=np.array(['love','face','care'])
c

array(['love', 'face', 'care'], dtype='<U4')

In [69]:
c.dtype.name

'str128'

A frequent error consists in calling array with multiple numeric arguments, rather than providing a single list of numbers as an argument.

In [72]:
a=np.array(2,3,5,7) #Wrong format of an array
a

ValueError: only 2 non-keyword arguments accepted

Array transforms sequences of sequences into two-dimensional arrays, sequences of sequences of sequences into three-dimensional arrays, and so on.

In [52]:
b=np.array([(1,2,3),(4,5,6)])
b

array([[1, 2, 3],
       [4, 5, 6]])

The type of the array can also be explicitly specified at creation time:

The function zeros creates an array full of zeros, the function ones creates an array full of ones, and the function empty creates an array whose initial content is random and depends on the state of the memory.

In [76]:
np.zeros((3,2), dtype=np.int16)

array([[0, 0],
       [0, 0],
       [0, 0]], dtype=int16)

In [77]:
d=np.zeros((2,3))
type(d)

numpy.ndarray

In [80]:
a=np.ones((3,4), dtype=np.int16)  # dtype can also be specified
a

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int16)

In [78]:
a.dtype.name

'int64'

To create sequences of numbers, NumPy provides a function analogous to range that returns arrays instead of lists.

In [81]:
np.arange(10,25,2) # 10 to 25 by the differebce of 3 

array([10, 12, 14, 16, 18, 20, 22, 24])

In [82]:
np.arange(0,2,0.3)  # it accepts float arguments

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

# Printing arrays

One-dimensional arrays are printed as rows, bidimensionals as matrices and tridimensionals as lists of matrices.

In [83]:
#  1-dimensional array
a=np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [84]:
a=np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [85]:
# 2-dimensional array
b=np.arange(12).reshape(4,3)
b

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [86]:
# 3-dimensional array
c=np.arange(24).reshape(2,3,4)
c

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [87]:
type(c)

numpy.ndarray

If an array is too large to be printed, NumPy automatically skips the central part of the array and only prints the corners

In [89]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# Basic operations

In [90]:
a=np.array([20,30,50,60])
a

array([20, 30, 50, 60])

In [91]:
b=np.arange(4)
b

array([0, 1, 2, 3])

In [92]:
c=a-b
c

array([20, 29, 48, 57])

In [93]:
b*2

array([0, 2, 4, 6])

In [94]:
10*np.sin(a)

array([ 9.12945251, -9.88031624, -2.62374854, -3.04810621])

In [95]:
a<35

array([ True,  True, False, False])

The matrix product can be performed using the dot function or method

In [96]:
a=np.array([[1,1],
            [0,1]])
b=np.array([[2,0],
           [3,4]])

In [149]:
# elementwise product
a*b

array([  0,  30, 100, 180])

In [150]:
# matrix product
a.dot(b)

310

In [151]:
 # another matrix product
np.dot(a,b)

310

Computing the sum of all the elements in the array, are implemented as methods of the ndarray class.

In [98]:
a=np.random.random((2,3))
a

array([[0.75611051, 0.76291577, 0.23013731],
       [0.15858798, 0.63199737, 0.43156675]])

In [99]:
a=np.random.random((2,3))
a

array([[0.6473517 , 0.10200881, 0.62569362],
       [0.5956797 , 0.03262308, 0.64295718]])

In [100]:
a.sum()

2.646314094650791

In [101]:
a.min()

0.032623080964814366

In [102]:
a.max()

0.647351695422899

In [103]:
a.mean()  #Mean(z)___R

0.4410523491084652

# Indexing, Slicing and Iterating

One-dimensional arrays can be indexed, sliced and iterated over, much like lists and other Python sequences.

In [104]:
a = np.arange(10)**3
a

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

In [105]:
a[4]

64

In [106]:
a[:2]

array([0, 1])

In [107]:
a[3:6]

array([ 27,  64, 125])

# Shape manipulation

Changing the shape of an array

In [125]:
a = np.floor(10*np.random.random((3,4)))
a

array([[4., 4., 7., 6.],
       [2., 9., 7., 1.],
       [1., 2., 1., 1.]])

In [110]:
a.shape

(3, 4)

In [112]:
a.size

12

In [111]:
# returns the array, flattened
a.ravel()

array([4., 5., 9., 1., 1., 9., 1., 4., 7., 4., 6., 3.])

In [123]:
# returns the array with a modified shape
n= a.reshape(6,2)   # 2*6 = 12
n

array([[4., 5.],
       [9., 1.],
       [1., 9.],
       [1., 4.],
       [7., 4.],
       [6., 3.]])

In [126]:
# returns the array, transposed
a.T  

array([[4., 2., 1.],
       [4., 9., 2.],
       [7., 7., 1.],
       [6., 1., 1.]])

In [127]:
a.T.shape

(4, 3)

In [128]:
a.shape

(3, 4)

In [131]:
np.arange(10).reshape(10,10)

ValueError: cannot reshape array of size 10 into shape (10,10)

In [178]:
np.array((5,6,7,10))

array([ 5,  6,  7, 10])

In [183]:
a=np.array((3,3.4))

In [184]:
a.dtype.name

'float64'

In [ ]:
string<Float<Int